<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // CAMBIO SI LAS TABLAS YA TIENEN DATOS

        // SE HACE PHP ARTISAN MIGRATE

        Schema::table('escuelas', function (Blueprint $table) {
            $table->integer('numeros_alumnos')->nullable();

        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        //
    }
    // LINEAS DE COMANDOS:
    // PHP ARTISAN MIGRATE QUE EJECUTA LAS MIGRACIONES
    // PHP ARTISAN MIGRATE:RESET QUE ELIMINA LAS MIGRACIONES Y LAS TABLAS
    // PHP ARTISAN MIGRATE:FRESH QUE ELIMINA LAS MIGRACIONES Y LAS TABLAS Y CREA LAS TABLAS
    // PHP ARTISAN DB:SEED QUE EJECUTA LAS SEEDS
    // PHP ARTISAN DB:SEED:RUN QUE EJECUTA LAS SEEDS
    // PHP ARTISAN DB:SEED:MAKE QUE CREA UNA SEED
    // PHP ARTISAN DB:SEED:MAKE:MODEL QUE CREA UNA SEED PARA UN MODELO
    // PHP ARTISAN DB:SEED:MAKE:MODEL:FACTORY QUE CREA UNA SEED PARA UN MODELO CON FACTORY
    // PHP ARTISAN DB:SEED:MAKE:MODEL:FACTORY:FACTORY QUE CREA UNA SEED PARA UN MODELO CON FACTORY CON FACTORY
    // PHP ARTISAN DB:SEED:MAKE:MODEL:FACTORY:FACTORY:FACTORY QUE CREA UNA SEED PARA UN MODELO CON FACTORY CON FACTORY CON FACTORY
    // PHP ARTISAN DB:SEED:MAKE:MODEL:FACTORY:FACTORY:FACTORY:FACTORY QUE CREA UNA SEED PARA UN MODELO CON FACTORY CON FACTORY CON FACTORY CON FACTORY
    // PHP ARTISAN DB:SEED:MAKE:MODEL:FACTORY:FACTORY:FACTORY:FACTORY:FACTORY QUE CREA UNA SEED PARA UN MODELO CON FACTORY CON FACTORY CON FACTORY CON FACTORY CON FACTORY
    // PHP ARTISAN DB:SEED:MAKE:MODEL:FACTORY:FACTORY:FACTORY:FACTORY:FACTORY:FACTORY QUE CREA UNA SEED PARA UN MODELO CON FACTORY CON FACTORY CON FACTORY CON FACTORY CON FACTORY CON FACTORY

};
